name: Matrix Build
on:
  workflow_dispatch: # Bu o deməkdir ki, biz bunu əllə işə salacağıq

jobs:
  build:
    runs-on: ${{ matrix.os }} # Matrix-dəki OS-ləri tək-tək yoxlayacaq
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [18, 20]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Print environment
        run: |
          node -v
          echo "OS: $RUNNER_OS"
